apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sharedservices
  name: manual-ecr-token-updater
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: manual-ecr-token-updater
    spec:
      containers:
      - image: tomarv2/devops/aws-jq-kubectl:0.0.1
        imagePullPolicy: IfNotPresent
        name: ecr-token-refresh
        env:
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: ecr_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: ecr_secret_access_key
        command:
            - /bin/sh
            - -c
            - |-
              set -x
              apk add jq 
              ls -ld /tmp/update-ecr-tokens.sh
              chmod +x /tmp/update-ecr-tokens.sh
              cat /tmp/update-ecr-tokens.sh
              sh /tmp/update-ecr-tokens.sh
              ACCOUNT=1234567890
              REGION=us-west-2
              SECRET_NAME=aws-ecr-registry
              EMAIL=anymail.doesnt.matter@email.com
              echo "get token..."
              TOKEN=`aws ecr get-login --region ${REGION} --registry-ids ${ACCOUNT} | cut -d' ' -f6`
              echo "ENV variables setup done."
              kubectl delete secret --ignore-not-found $SECRET_NAME -n spinnaker
              kubectl create secret docker-registry $SECRET_NAME -n spinnaker \
              --docker-server=https://${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com \
              --docker-username=AWS \
              --docker-password="${TOKEN}" \
              --docker-email="${EMAIL}"
              echo "Secret created by name. $SECRET_NAME"
              echo "All done."
              sleep  36000
        volumeMounts:
          - name: kubectl-config
            mountPath: "/root/.kube/config"
            subPath: config
          - name: ecr-token-config
            mountPath: "/tmp/update-ecr-tokens.sh"
            subPath: update-ecr-tokens.sh
      volumes:
      - name: kubectl-config
        secret:
          secretName: kubectl-config
          items:
          - key: config
            path: config
      - name: ecr-token-config
        configMap: 
          name: ecr-token-updater-script
          items:
          - key: update-ecr-tokens.sh
            path: update-ecr-tokens.sh